### ISSUE TITLE
Replace hsearch with custom hash table

### ISSUE THREAD

**Issue by xflouris** [Pas-Kapli/mptp#76]
Replace the GNU 'hsearch' function with a custom hash table implementation as the `hsearch' function is implemented differently on Linux and Mac (MAC deallocates the associated data automatically, while Linux does not), causing either memory leaks or double frees.

**Comment by algomaus** [comment]
Can't we just solve it with an ifdef, too?

**Comment by xflouris** [comment]
@algomaus : yes we can, but there are three things:
1. We don't know if this different behaviour is only on MAC (I know it is on BSD as well).
2. Some older libc do not have the hsearch functions as it is a GNU function
3. I spotted this problem like a year ago when working on fastdate, and have since then implemented a fix, so it is just a copy-paste for me.

**Comment by xflouris** [comment]
finished.
