### ISSUE TITLE
libgsl not detected

### ISSUE THREAD

**Issue by PrestonMcDonald** [Pas-Kapli/mptp#86]
I'm working on a shared cluster with LMod enviromental modules. I loaded gsl 2.4 and attempted to compile mptp 0.2.4. The library was not detected during configuration, despite being listed in the LD_LIBRARY_PATH.

**Comment by xflouris** [comment]
Hi @PrestonMcDonald ,
I think the easiest solution would be to try the [Releases](https://github.com/Pas-Kapli/mptp/releases/tag/v0.2.4) tab, and download the statically pre-compiled binary which includes libgsl and see if that runs on the cluster's OS.

The other option would be to compile manually. I'm not sure if LD_LIBRARY_PATH is checked by default (probably you will need to override LDFLAGS), but I think the following should work:

```
export LDFLAGS='-L/path/to/libgsl/'
./configure
```

Hope this helps,
tomas

**Comment by PrestonMcDonald** [comment]
Exporting to LDFLAGS solved the issue. Thanks
