### ISSUE TITLE
Running mPTP on amino acid alignment

### ISSUE THREAD

**Issue by Zichen-Zhou** [Pas-Kapli/mptp#88]
Hi mPTP team,

I'm trying to run mPTP on an amino acid tree. I tried to test the min branch length on the amino acid alignment, and it keeps popping 'FASTA file does not contain equal size sequences' but all my sequences are length at 140bp. I tried all methods to check the fasta file but I don't think it has such problem. May I know how I can solve the issue? Thanks.

Regards,
Zichen

**Comment by stamatak** [comment]
can you please post your question on the mPTP google group? Thank you.
